#server
server:
  port: 10000

#MyBatis
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: onestep
      password: 1234

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  #multipart
  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB

root:
  dir: C:/onestep/uploadFiles/