#server
server:
  port: 10000

spring:
  datasource:
    hikari:
      #MyBatis
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: onestep
      password: 1234

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  #multipart
  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB

  # 오로지 테이블 생성용으로 jpa를 사용함
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
    # open-in-view: false

root:
  dir: C:/onestep/uploadFiles/